MSW.Web/MSW.Web/Controllers/LocalizacaoController.cs
using System;
using System.Linq;
using MSW.Web.Models;
using System.Web.Mvc;
using MSW.Web.Helpers;
using MSW.Web.Models.Request;
using MSW.Web.Models.Response;
using System.Collections.Generic;
using Newtonsoft.Json;
using MSW.Web.Helpers.Extensions;
using PagedList;
using System.Web;

namespace MSW.Web.Controllers
{
    public class LocalizacaoController : PaginacaoController
    {
        private readonly OmintHttpRequest request = new OmintHttpRequest();

        public ActionResult BuscaLocalizacao()
        {
            RedeTipoAtendimentoBeneficiario atendimento = Contexto.DadosUsuario?.DadosRede.TiposAtendimentoPadrao.FirstOrDefault(x => x.TipoView.Equals(Request.QueryString["TipoAtendimento"], StringComparison.OrdinalIgnoreCase));
            Endereco endereco = Contexto.DadosUsuario?.Enderecos.FirstOrDefault(x => string.Equals("RES", x.TipoEndereco.Codigo, System.StringComparison.OrdinalIgnoreCase));

            BuscaLocalizacaoRequest buscaLocalizacao = new BuscaLocalizacaoRequest
            {
                Atendimento = atendimento?.DescricaoTipoAtendimento,
                Especialidade = Request.QueryString["Especialidade"],
                Cep = endereco?.Logradouro.CEP,
                Cidade = endereco?.Logradouro.Municipio.Nome,
                CodigoEstado = endereco?.Logradouro.Municipio.CodigoUF,
                Vinculo = Contexto.DadosUsuario?.Vinculo,
                Rede = Request.QueryString["Rede"] ?? "",
                TipoAtendimento = Request.QueryString["TipoAtendimento"],
                CodigoEspecialidade = Request.QueryString["CodigoEspecialidade"]
            };

            return View(buscaLocalizacao);
        }

        [ChildActionOnly]
        public ActionResult ObterRegioes(BuscaEspecialidadeRequest request)
        {
            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterRegioes", request);

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;
                return PartialView("_BuscaRegiao", new RegioesResponse());
            }

            RegioesResponse resultadoOperacao = response.ObterResultado<RegioesResponse>();

            if (Contexto.DadosUsuario != null && Contexto.DadosUsuario.Localizacao == null)
            {
                Contexto.DadosUsuario.Localizacao = resultadoOperacao.Data;
            }

            return PartialView("_BuscaRegiao", resultadoOperacao);
        }

        [HttpPost, ActionName("BuscaRegiao")]
        public ActionResult ObterPorRegiao(BuscaRegiaoRequest request)
        {
            object reqParams = new
            {
                Vinculo = request.Vinculo,
                Rede = request.Rede ?? "",
                TipoAtendimento = request.TipoAtendimento,
                CodigoEspecialidade = request.CodigoEspecialidade,
                CodigoEstado = request.CodigoEstado,
                Cidade = request.Cidade,
                Bairro = request.Bairro ?? string.Empty,
                Inativos = request.Inativos
            };

            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterPorRegiao", reqParams);

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;
                return View("~/Views/Resultados/ResultadoBusca.cshtml", new ResultadoBuscaResponse());
            }

            ResultadoBuscaResponse resultadoOperacao = response.ObterResultado<ResultadoBuscaResponse>();
            List<Prestador> prestadores = resultadoOperacao.Data.OrderByDescending(x => x.ScoreTotal).ToList();

            if (prestadores != null)
            {
                Contexto.AdicionarDados(Consts.RESULTADO_PESQUISA_SEM_FILTRO, prestadores);
                Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES, prestadores);
                Contexto.AdicionarDados(Consts.TIPO_FILTRO_BUSCA, ContextoBuscaFiltro.BuscaPrestadores.ToString());
            }

            resultadoOperacao.QuantidadeLocalizados = resultadoOperacao.Data.Count;

            resultadoOperacao.DefaultLat = prestadores?.Where(x => !string.IsNullOrEmpty(x.GmLatitude))?.FirstOrDefault()?.GmLatitude ?? Consts.LATITUDE_PADRAO_BRASIL;
            resultadoOperacao.DefaultLng = prestadores?.Where(x => !string.IsNullOrEmpty(x.GmLongitude))?.FirstOrDefault()?.GmLongitude ?? Consts.LONGITUDE_PADRAO_BRASIL;
            resultadoOperacao.MarcadoresGoogleMapsPosition = JsonConvert.SerializeObject(prestadores?.GroupBy(x =>
                                                                                                                  new
                                                                                                                  {
                                                                                                                      x.GmLatitude,
                                                                                                                      x.GmLongitude,
                                                                                                                      x.DescricaoPrestador
                                                                                                                  })
                                                                                                                  ?.Where(w => !string.IsNullOrEmpty(w.Key.GmLatitude) && !string.IsNullOrEmpty(w.Key.GmLongitude))
                                                                                                                  ?.Select(x => new { lat = x.Key.GmLatitude, lng = x.Key.GmLongitude, nome = x.Key.DescricaoPrestador }));


            ViewBag.PagedList = prestadores.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);
            return View("~/Views/Resultados/ResultadoBusca.cshtml", resultadoOperacao);
        }

        [HttpPost, ActionName("BuscaProximidadeResidencia")]
        public ActionResult ObterPorProximidade(BuscaProximidadeRequest request)
        {
            object requestParams = new
            {
                Vinculo = request.Vinculo,
                Rede = request.Rede ?? "",
                TipoAtendimento = request.TipoAtendimento,
                CodigoEspecialidade = request.CodigoEspecialidade,
                Inativos = request.Inativos,
                BuscaProximidadeTipo = request.BuscaProximidadeTipo
            };

            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterPorProximidade", requestParams);

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;
                return View("~/Views/Resultados/ResultadoBuscaProximidade.cshtml", new LocalizacaoResponse());
            }

            LocalizacaoResponse resultadoOperacao = response.ObterResultado<LocalizacaoResponse>();
            List<Prestador> prestadores = resultadoOperacao.Data.Select(s => s.Prestador).OrderByDescending(s => s.ScoreTotal).ToList();

            if (resultadoOperacao != null)
            {
                Contexto.AdicionarDados(Consts.RESULTADO_PESQUISA_SEM_FILTRO_LOCALIDADE, resultadoOperacao.Data);
                Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE, resultadoOperacao.Data);
                Contexto.AdicionarDados(Consts.TIPO_FILTRO_BUSCA, ContextoBuscaFiltro.BuscaPrestadoresLocalizacao.ToString());
            }

            resultadoOperacao.Atendimento = request.Atendimento;
            resultadoOperacao.Especialidade = request.Especialidade;
            resultadoOperacao.BuscaProximidadeTipo = request.BuscaProximidadeTipo;

            resultadoOperacao.QuantidadeLocalizados = prestadores.Count;

            resultadoOperacao.DefaultLat = prestadores?.Where(x => !string.IsNullOrEmpty(x.GmLatitude))?.FirstOrDefault()?.GmLatitude ?? Consts.LATITUDE_PADRAO_BRASIL;
            resultadoOperacao.DefaultLng = prestadores?.Where(x => !string.IsNullOrEmpty(x.GmLongitude))?.FirstOrDefault()?.GmLongitude ?? Consts.LONGITUDE_PADRAO_BRASIL;
            resultadoOperacao.MarcadoresGoogleMapsPosition = JsonConvert.SerializeObject(prestadores
                                                                                                                  ?.GroupBy(x =>
                                                                                                                  new
                                                                                                                  {
                                                                                                                      x.GmLatitude,
                                                                                                                      x.GmLongitude
                                                                                                                  })
                                                                                                                  ?.Where(w => !string.IsNullOrEmpty(w.Key.GmLatitude) && !string.IsNullOrEmpty(w.Key.GmLongitude))
                                                                                                                  ?.Select(x => new { lat = x.Key.GmLatitude, lng = x.Key.GmLongitude }));

            ViewBag.PagedList = resultadoOperacao.Data.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);

            return View("~/Views/Resultados/ResultadoBuscaProximidade.cshtml", resultadoOperacao);
        }

        [HttpPost, ActionName("BuscaProximidadeLocal")]
        public ActionResult ObterPorProximidadeAtual(BuscaProximidadeLocalRequest request)
        {
            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterPorProximidadeAtual", request);

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;

MSW.Web/MSW.Web/Views/Localizacao/BuscaLocalizacao.cshtml
@model BuscaLocalizacaoRequest

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" id="formBuscaLocalizacao">

    <div class="row">
        <div class="col-xs-12">
            <h4 class="titulo-busca-avancada-omint">Busca por Proximidade</h4>
        </div>
    </div>
    <div class="row row-space">
        <div class="col-xs-2" id="buscaProximosAMim">
            <span><a href="javascript:void(0);" id="btnProximosAMim">Próximos a mim</a></span>
        </div>

        @if (!string.IsNullOrEmpty(Model.Vinculo))
        {
            <div class="col-xs-4">
                <span><a href="javascript:void(0);" id="btnProximosAMinhaResidencia">Proximos a minha residência @Model.Cep - @Model.Cidade/@Model.CodigoEstado</a></span>
            </div>
        }
    </div>

    <div class="row row-space">
        <div class="col-xs-12">
            <h4 class="titulo-busca-avancada-omint">Busca por Região</h4>
        </div>
    </div>

    @{ Html.RenderAction("ObterRegioes", "Localizacao", new BuscaEspecialidadeRequest { Vinculo = Model.Vinculo, Rede = Model.Rede, TipoAtendimento = Model.TipoAtendimento, CodigoEspecialidade = Model.CodigoEspecialidade }); }
 
    @Html.HiddenFor(x => x.Vinculo)
    @Html.HiddenFor(x => x.Rede)
    @Html.HiddenFor(x => x.CodigoEspecialidade)
    @Html.HiddenFor(x => x.Atendimento)
    @Html.HiddenFor(x => x.TipoAtendimento)
    @Html.HiddenFor(x => x.Especialidade)

    @Html.Hidden("latitude")
    @Html.Hidden("longitude")
    @Html.Hidden("buscaProximidadeTipo")

    @Html.Hidden("Cidade")
    @Html.Hidden("CodigoEstado")
    @Html.Hidden("Bairro")
</form>

@section scripts{
    <script src="~/Content/js/busca.rede-credenciada.js"></script>
    <script>
        $(document).on('ready', function () {

            var buscaLocalizacao = new buscaRedeCredenciada.BuscaLocalizacao({
                form: '#formBuscaLocalizacao',
                urlObterCidades: '@Url.Action("ObterCidades", "Localizacao")',
                urlObterBairros: '@Url.Action("ObterBairros", "Localizacao")',
                urlBuscaProximidadeLocal: '@Url.Action("BuscaProximidadeLocal", "Localizacao")',
                urlBuscaRegiao: '@Url.Action("BuscaRegiao", "Localizacao")',
                urlBuscaProximidadeResidencia: '@Url.Action("BuscaProximidadeResidencia", "Localizacao")',
                buscaSelectors: {
                    ddlCidade: '#ddlCidade',
                    ddlEstado: '#ddlEstado',
                    ddlBairro: '#ddlBairro',
                    hdnCidade: '#Cidade',
                    hdnCodigoEstado: '#CodigoEstado',
                    hdnBairro: '#Bairro',
                    buscaProximidadeTipo: '#buscaProximidadeTipo',
                    latitude: '#latitude',
                    longitude: '#longitude',
                    btnBuscaProximosLocalizacao: '#buscaProximosAMim',
                    btnBuscaRegiao: '#btnBuscaRegiao',
                    btnBuscaProximosAMinhaResidencia: '#btnProximosAMinhaResidencia',
                }
            });

            buscaLocalizacao.configurarBuscaLocalizacao();
        });

    </script>
}

MSW.Web/MSW.Web/Views/Localizacao/_BuscaRegiao.cshtml
@model RegioesResponse

<div class="row row-space">
    <div class="col-xs-2">
        <div class="form-group">
            @Html.LabelFor(x => x.Estado)
            @Html.DropDownListFor(x => x.Estado, Model.ListaEstados, new { @class= "ddl-padrao ddl-estado", @id ="ddlEstado" })
        </div>
    </div>
    <div class="col-xs-3">
        <div class="form-group">
            @Html.LabelFor(x => x.Cidade)
            @Html.DropDownListFor(x => x.Cidade, Model.ListaCidades, new { @class= "ddl-padrao ddl-cidade-bairro", @id = "ddlCidade" })
        </div>
    </div>
    <div class="col-xs-3">
        <div class="form-group">
            @Html.LabelFor(x => x.Bairro)
            @Html.DropDownListFor(x => x.Cidade, Model.ListaBairros, new { @class = "ddl-padrao ddl-cidade-bairro", @id = "ddlBairro" })
        </div>
    </div>
    <div class="col-xs-3">
        <button type="button" id="btnBuscaRegiao" class="btn-omintexpress">Ok</button>
    </div>
</div>