MSW.Web/MSW.Web/Controllers/FiltroMenuController.cs
using System.IO;
using System.Linq;
using System.Web.Mvc;
using MSW.Web.Models;
using MSW.Web.Helpers;
using MSW.Web.Models.Response;
using System.Collections.Generic;
using PagedList;
using MSW.Web.Helpers.Extensions;
using System;
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;
using MSW.Web.Helpers.GMaps;

namespace MSW.Web.Controllers
{
    public class FiltroMenuController : Controller
    {
        [ChildActionOnly]
        public ActionResult MenuFiltro()
        {
            FiltroMenu filtroMenu = ObterFiltroMenu();
            return PartialView("~/Views/Shared/_FiltroMenuLateral.cshtml", filtroMenu);
        }

        private static FiltroMenu ObterFiltroMenu()
        {
            FiltroMenu filtroMenu = new FiltroMenu();

            ContextoBuscaFiltro contextoBusca;
            System.Enum.TryParse(Contexto.ObterDados<string>(Consts.TIPO_FILTRO_BUSCA), out contextoBusca);

            List<Prestador> prestadores = contextoBusca == ContextoBuscaFiltro.BuscaPrestadores ?
                    Contexto.ObterDados<List<Prestador>>(Consts.LISTA_DADOS_PRESTADORES) :
                    Contexto.ObterDados<List<DadosLocalizacao>>(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE)?.Select(s => s.Prestador).ToList();

            filtroMenu.AdicionarEspecialidades(prestadores);
            filtroMenu.AdicionarAvaliacoes(prestadores);
            filtroMenu.AdicionarCidades(prestadores);
            filtroMenu.AdicionarEstados(prestadores);
            filtroMenu.AdicionarServico(prestadores);

            var planosLogado = Contexto.DadosUsuario?.DadosRede
                                          .Planos
                                          .Select(x => x.CodigoRede)
                                          .ToArray();

            filtroMenu.AdicionarPlano(planosLogado != null ? prestadores.Where(x => planosLogado.Contains(x.CodigoRede)) : prestadores);

            filtroMenu.AdicionarRede(planosLogado != null ? prestadores.Where(x => planosLogado.Contains(x.CodigoRede)).GroupBy(s => new { s.CodigoRede, s.DescricaoRede }).Select(s => new AgregadorPlanoRede { CodigoRede = s.Key.CodigoRede, Descricao = s.Key.DescricaoRede, Quantidade = s.Count() }).ToArray()
                : prestadores.GroupBy(s => s.CodigoRede).Select(s => new AgregadorPlanoRede { CodigoRede = s.Key, Quantidade = s.Count() }).ToArray());

            filtroMenu.QuantidadeLocalizados = prestadores?.Count() ?? 0;
            return filtroMenu;
        }

        [HttpPost]
        public ActionResult Filtrar(FiltroMultiplo filtro)
        {
            if (filtro == null)
            {
                filtro = new FiltroMultiplo();
            }

            System.Web.HttpContext.Current.Items[Consts.MULTIPLOS_FILTROS] = filtro;

            ContextoBuscaFiltro contextoBusca;
            Enum.TryParse(Contexto.ObterDados<string>(Consts.TIPO_FILTRO_BUSCA), out contextoBusca);

            if (contextoBusca == ContextoBuscaFiltro.BuscaPrestadores)
            {
                List<Prestador> prestadoresFiltrados = Contexto.ObterDados<List<Prestador>>(Consts.LISTA_DADOS_PRESTADORES)
                                                           ?.Where(w => (!filtro.Estados.Any() || filtro.Estados.Contains(w.CodigoEstado.Trim()))
                                                           && (!filtro.Cidades.Any() || filtro.Cidades.Contains(w.EnderecoCidade))
                                                           && (!filtro.Especialidades.Any() || filtro.Especialidades.Any(w.Especialidades.Contains)))
                                                           .ToList() ?? new List<Prestador>();

                Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES, prestadoresFiltrados);

                IPagedList<Prestador> prestadores = prestadoresFiltrados.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);

                return new JsonResult
                {
                    Data = new ResultadoFiltroResponse { ViewResult = RenderRazorViewToString("~/Views/Shared/_ListaResultadoBusca.cshtml", prestadores) },
                    MaxJsonLength = int.MaxValue
                };
            }

            List<DadosLocalizacao> dadosLocalizacao = Contexto.ObterDados<List<DadosLocalizacao>>(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE)
                ?.Where(w => filtro.Cidades.Contains(w.Prestador.EnderecoCidade.Trim()))
                .ToList();

            Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE, dadosLocalizacao);

            IPagedList<DadosLocalizacao> localizacao = dadosLocalizacao.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);

            return new JsonResult
            {
                Data = new ResultadoFiltroResponse { ViewResult = RenderRazorViewToString("~/Views/Shared/_ListaResultadoBuscaProximidade.cshtml", localizacao) },
                MaxJsonLength = int.MaxValue
            };
        }

        [HttpPost]
        public ActionResult FiltrarPorServico(string servico)
        {
            ContextoBuscaFiltro contextoBusca;
            Enum.TryParse(Contexto.ObterDados<string>(Consts.TIPO_FILTRO_BUSCA), out contextoBusca);

            string siglaServico = "Médico".Equals(servico, System.StringComparison.OrdinalIgnoreCase) ? "M" : "O";

            IEnumerable<string> codigosRede = ObterCodigosRede(siglaServico);

            if (contextoBusca == ContextoBuscaFiltro.BuscaPrestadores)
            {
                List<Prestador> prestadoresFiltrados = Contexto.ObterDados<List<Prestador>>(Consts.LISTA_DADOS_PRESTADORES)
                                                              ?.Where(w => codigosRede.Contains(w.CodigoRede.Trim()))
                                                               .ToList() ?? new List<Prestador>();

                Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES, prestadoresFiltrados);

                IPagedList<Prestador> prestadores = prestadoresFiltrados.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);
                return new JsonResult
                {
                    Data = new ResultadoFiltroResponse { ViewResult = RenderRazorViewToString("~/Views/Shared/_ListaResultadoBusca.cshtml", prestadores) },
                    MaxJsonLength = int.MaxValue
                };
            }

            List<DadosLocalizacao> dadosLocalizacao = Contexto.ObterDados<List<DadosLocalizacao>>(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE)
                                                              ?.Where(w => codigosRede.Contains(w.Prestador.CodigoRede.Trim()))
                                                               .ToList() ?? new List<DadosLocalizacao>();

            Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE, dadosLocalizacao);

            IPagedList<DadosLocalizacao> localizacao = dadosLocalizacao.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);

            return new JsonResult
            {
                Data = new ResultadoFiltroResponse { ViewResult = RenderRazorViewToString("~/Views/Shared/_ListaResultadoBuscaProximidade.cshtml", localizacao) },
                MaxJsonLength = int.MaxValue
            };
        }

        [HttpPost]
        public ActionResult FiltrarPorRede(string codigoRede)
        {
            ContextoBuscaFiltro contextoBusca;
            Enum.TryParse(Contexto.ObterDados<string>(Consts.TIPO_FILTRO_BUSCA), out contextoBusca);

            Contexto.AdicionarDados(Consts.CODIGO_REDE, codigoRede);
            if (contextoBusca == ContextoBuscaFiltro.BuscaPrestadores)
            {
                List<Prestador> prestadoresFiltrados = Contexto.ObterDados<List<Prestador>>(Consts.LISTA_DADOS_PRESTADORES)
                                        ?.Where(w => codigoRede == w.CodigoRede)
                                        .ToList() ?? new List<Prestador>();

                Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES, prestadoresFiltrados);

                IPagedList<Prestador> prestadores = prestadoresFiltrados.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);
                return new JsonResult
                {
                    Data = new ResultadoFiltroResponse { ViewResult = RenderRazorViewToString("~/Views/Shared/_ListaResultadoBusca.cshtml", prestadores) },
                    MaxJsonLength = int.MaxValue
                };
            }

            List<DadosLocalizacao> dadosLocalizacao = Contexto.ObterDados<List<DadosLocalizacao>>(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE)
                                                               ?.Where(w => codigoRede == w.Prestador.CodigoRede)
                                                               .ToList();

            Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE, dadosLocalizacao);

            IPagedList<DadosLocalizacao> localizacao = dadosLocalizacao.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);

            return new JsonResult
            {
                Data = new ResultadoFiltroResponse { ViewResult = RenderRazorViewToString("~/Views/Shared/_ListaResultadoBuscaProximidade.cshtml", localizacao) },
                MaxJsonLength = int.MaxValue
            };
        }

        [HttpPost]
        public ActionResult FiltrarPorPlano(string codigoPlano)
        {
            ContextoBuscaFiltro contextoBusca;
            Enum.TryParse(Contexto.ObterDados<string>(Consts.TIPO_FILTRO_BUSCA), out contextoBusca);

            var redePlano = ObterFiltroMenu().ObterRedeDoPlano(codigoPlano);

            if (contextoBusca == ContextoBuscaFiltro.BuscaPrestadores)
            {
                List<Prestador> prestadoresFiltrados = Contexto.ObterDados<List<Prestador>>(Consts.LISTA_DADOS_PRESTADORES)
                                        ?.Where(w => redePlano.Contains(w.CodigoRede))

MSW.Web/MSW.Web/Views/Shared/_FormularioBuscaNome.cshtml
@model ResultadoBuscaResponse

<div class="row no-print">
    <div class="col-lg-4">
        <span class="titulo-busca-rede">BUSCA REDE CREDENCIADA</span>
    </div>
    <div class="col-lg-2">
    </div>
    <div class="col-lg-3">
        <span><a href="@Url.Action("BuscaAvancada", "BuscaPrestadores", new { Rede = Model.CodigoRede })">Busca estruturada</a></span>
    </div>
</div>
<div class="row row-space no-print">
    <div class="col-lg-7">
        <div class="box-input-search">
            @Html.TextBoxFor(x => x.Nome, new { @class = "input-search-prestadores", autofocus="true" })
            <button type="submit" class="button" id="btnBuscaForm"></button>
        </div>
    </div>
</div>
<div class="row row-space">
    <div class="col-lg-3">
        @*<span>Consulte a relação de <a href="javascript:void(0);">credenciais inativos</a></span>*@
    </div>
    <div class="col-lg-9">
        @*<span>Está em dúvida? Consulte o Glossário de especialidades <a href="javascript:void(0);">aqui</a></span>*@
    </div>
</div>

@Html.Hidden("Inativos", Model.Inativos)
@Html.Hidden("Vinculo", Model.Vinculo)
@Html.Hidden("codigoRede", Model.CodigoRede)
@Html.Hidden("descricaoRede", Model.DescricaoRede)
@Html.Hidden("plano", Model.Plano)

MSW.Web/MSW.Web/Views/Shared/_ListaResultadoBusca.cshtml
@model IPagedList<Prestador>

<div class="row row-space-menu" id="resultado">
    @{ Html.RenderAction("MenuFiltro", "FiltroMenu"); }
    <div class="col-xs-9" style="width:73%">
        <div id="map-canvas" class="no-print" style="width: 100%; height: 272px;"></div>
        <div>
            <div class="col-md-10" id="resultDetalhes">
                <div class="row">
                    <div class="prestador-preferencial-title no-print">
                        <img src="~/Content/img/prestador-preferencial.png" class="logo-align" />
                    </div>
                    <div class="rotas-title no-print">
                        <img src="~/Content/img/rotas.png" class="logo-align" />
                    </div>
                    <div class="imprimir-selecionados-title no-print">
                        <a href="javascript:void(0);" id="btnImprimir"><img src="~/Content/img/imprimir-selecionados.png" class="logo-align" /></a>
                    </div>
                    <div class="ordenar-combo-title no-print">
                        <select class="combobox-ordenar-por" id="ddlOrdenacao">
                            <option selected value="">Ordenar Por</option>
                            <option value="nome">Nome</option>
                            <option value="prestadorPreferencial">Prestador Preferencial</option>
                            <option value="distancia">Distância</option>
                        </select>
                    </div>
                    <div class="result-omint-container">
                        @if (Model.Any())
                        {
                            int i = 0;
                            <table class="table-result">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="no-print">
                                            <td>
                                                <div class="div-table-container">
                                                    <div class="col-xs-2">
                                                        @if (item.ScoreTotal >= int.Parse(ConfigurationManager.AppSettings["buscaCredenciada:NrPrestadorPreferencial"]))
                                                        {
                                                            <img src="~/Content/img/logo1.png" class="logo-prestador-align" />
                                                        }
                                                    </div>
                                                    <div class="col-xs-10 div-prestador" data-prestador="@item.DescricaoPrestador" data-endereco="@item.TipoLogradouro @item.EnderecoRua, @item.EnderecoNumero @item.EnderecoComplemento" data-telefone="@(item.Telefones.Any() ? item.Telefones[0].FormatPhone() : item.TelefoneFormatado)">
                                                        <div class="col-xs-9">
                                                            <span class="span-texto-conteudo-prestador">
                                                                <a href="javascript:void(0);">@item.DescricaoPrestador</a>
                                                            </span>
                                                            <div class="span-texto-conteudo" style="display:inline-block">
                                                                <div class="endereco-completo" style="display:inline-block">
                                                                    @item.TipoLogradouro @item.EnderecoRua, @item.EnderecoNumero @item.EnderecoComplemento, @item.EnderecoBairro
                                                                    <span class="endereco-cidade"> - @item.EnderecoCidade - @item.CodigoEstado</span>    
                                                                </div>
                                                                <span class="phone">@(item.Telefones.Any() ? item.Telefones[0].FormatPhone() : item.TelefoneFormatado)</span>    
                                                                <span class="especialidade">Especialidades</span>
                                                                <span class="especialidade">@(item.Especialidades.Any() ? string.Join("/",item.Especialidades) : item.DescricaoEspecialidade)</span>
                                                            </div><br />
                                                        </div>
                                                        <div class="col-xs-3 div-mapa-ver-completo no-print" data-lat="@item.GmLatitude" data-lng="@item.GmLongitude">
                                                            <img src="~/Content/img/pim-mapa-omint.png" />
                                                            <input type="checkbox" class="chkImprimir" />
                                                            @if (!string.IsNullOrWhiteSpace(item.Distancia))
                                                            {
                                                                <br /><small>@item.Distancia</small>
                                                            }
                                                        </div>
                                                    </div>
                                                </div>
                                                @Html.Hidden("CodigoPrestador_" + i, item.CodigoPrestador)
                                                @Html.Hidden("Rede_" + i, item.CodigoRede)
                                                @Html.Hidden("NomePrestador_" + i, item.DescricaoPrestador)
                                                @Html.Hidden("Registro_" + i, item.DescricaoRegistro)
                                                @Html.Hidden("Endereco_" + i, string.Format("{0} {1}, {2}", item.TipoLogradouro, item.EnderecoRua, item.EnderecoNumero))
                                                @Html.Hidden("Complemento_" + i, item.EnderecoComplemento)
                                                @Html.Hidden("Bairro_" + i, item.EnderecoBairro)
                                                @Html.Hidden("Cidade_" + i, item.EnderecoCidade.Trim())
                                                @Html.Hidden("Estado_" + i, item.CodigoEstado)
                                                @Html.Hidden("Cep_" + i, item.CodigoCep)
                                                @Html.Hidden("SrEndereco_" + i, item.SrEndereco)
                                                @Html.Hidden("DescricaoObservacao_" + i, item.DescricaoObservacao)
                                                @Html.Hidden("DataDescredenciamento_" + i, item.DataDescredenciamento)
                                                @Html.Hidden("NrAvaliacao_" + i, item.NrAvaliacao)
                                                @Html.Hidden("Telefone_" + i, item.Telefones.Any() ? item.Telefones[0].FormatPhone() : item.TelefoneFormatado)
                                                @Html.Hidden("ScoreTotal_" + i, item.ScoreTotal)
                                                @Html.Hidden("Latitude_" + i, item.GmLatitude)
                                                @Html.Hidden("Longitude_" + i, item.GmLongitude)
                                            </td>
                                        </tr>

                                        i++;
                                    }
                                </tbody>
                            </table>
                            <div class="row no-print" style="margin-left:30px">
                                @Html.PagedListPager(Model, page => Url.Action("PaginarPrestadores", "BuscaPrestadores", new { page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
                            </div>
                        }
                        else
                        {
                            <div class="col-lg-12">
                                @if (ViewBag.Erro != null)
                                {
                                    <span>@ViewBag.Erro</span>
                                }
                                else
                                {
                                    <span>A busca não gerou resultados!</span>
                                }
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-xs-2 no-print">
                <div class="espaco-banner-img"
                     style="background-image: url(@Url.Content("~/Content/img/busca/medico-1.jpg"))">
                </div>
                <div class="espaco-banner-img"
                     style="background-image: url(@Url.Content("~/Content/img/busca/medico-2.jpg"))">
                </div>
                <div class="espaco-banner-img"
                     style="background-image: url(@Url.Content("~/Content/img/busca/medico-3.jpg"))">
                </div>
            </div>
        </div>
    </div>
</div>

MSW.Web/MSW.Web/Views/Shared/_ListaResultadoBuscaProximidade.cshtml
@model IPagedList<DadosLocalizacao>

<div class="row row-space-menu" id="resultado">
    @{ Html.RenderAction("MenuFiltro", "FiltroMenu"); }
    <div class="col-xs-9" style="width:73%">
        <div id="map-canvas" class="no-print" style="width: 100%; height: 272px;"></div>
        <div>
            <div class="col-md-10" id="resultDetalhes">
                <div class="row">
                    <div class="prestador-preferencial-title no-print">
                        <img src="~/Content/img/prestador-preferencial.png" class="logo-align" />
                    </div>
                    <div class="rotas-title no-print">
                        <img src="~/Content/img/rotas.png" class="logo-align" />
                    </div>
                    <div class="imprimir-selecionados-title no-print">
                        <a href="javascript:void(0);" id="btnImprimir"><img src="~/Content/img/imprimir-selecionados.png" class="logo-align" /></a>
                    </div>
                    <div class="ordenar-combo-title no-print">
                        <select class="combobox-ordenar-por" id="ddlOrdenacao">
                            <option selected value="">Ordenar Por</option>
                            <option value="nome">Nome</option>
                            <option value="prestadorPreferencial">Prestador Preferencial</option>
                            <option value="distancia">Distância</option>
                        </select>
                    </div>
                    <div class="result-omint-container">
                        @if (Model.Any())
                        {
                            <table class="table-result">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        int i = 0;
                                        <tr class="no-print">
                                            <td>
                                                <div class="div-table-container">
                                                    <div class="col-xs-2">
                                                        @if (item.Prestador.ScoreTotal >= int.Parse(ConfigurationManager.AppSettings["buscaCredenciada:NrPrestadorPreferencial"]))
                                                        {
                                                            <img src="~/Content/img/logo1.png" class="logo-prestador-align" />
                                                        }
                                                    </div>
                                                    <div class="col-xs-10 div-prestador" data-prestador="@item.Prestador.DescricaoPrestador" data-endereco="@item.Prestador.TipoLogradouro @item.Prestador.EnderecoRua, @item.Prestador.EnderecoNumero @item.Prestador.EnderecoComplemento" data-telefone="@item.Prestador.TelefoneFormatado">
                                                        <div class="col-xs-9">
                                                            <span class="span-texto-conteudo-prestador">
                                                                <a href="javascript:void(0);">@item.Prestador.DescricaoPrestador</a>
                                                            </span>
                                                            @*<span class="span-texto-conteudo" style="display:inline-block">@item.Prestador.TipoLogradouro @item.Prestador.EnderecoRua, @item.Prestador.EnderecoNumero @item.Prestador.EnderecoComplemento, @item.Prestador.EnderecoBairro  <span class="phone">@item.Prestador.TelefoneFormatado</span></span><br />*@
                                                            <div class="span-texto-conteudo" style="display:inline-block">
                                                                <div class="endereco-completo" style="display:inline-block">
                                                                    @item.Prestador.TipoLogradouro @item.Prestador.EnderecoRua, @item.Prestador.EnderecoNumero @item.Prestador.EnderecoComplemento, @item.Prestador.EnderecoBairro
                                                                    <span class="endereco-cidade"> - @item.Prestador.EnderecoCidade - @item.Prestador.CodigoEstado</span>
                                                                </div>
                                                                <span class="phone">@item.Prestador.TelefoneFormatado</span>
                                                                <span class="especialidade">Especialidades</span>
                                                                <span class="especialidade">@item.Prestador.DescricaoEspecialidade</span>
                                                            </div><br />
                                                        </div>
                                                        <div class="col-xs-3 div-mapa-ver-completo no-print" data-lat="@item.Prestador.GmLatitude" data-lng="@item.Prestador.GmLongitude">
                                                            <img src="~/Content/img/pim-mapa-omint.png" />
                                                            <input type="checkbox" class="chkImprimir no-print" />
                                                            @if (item.Distancia > 0)
                                                            {
                                                                <br /><small>@string.Format("{0:N2} km", item.Distancia)</small>
                                                            }
                                                        </div>
                                                    </div>
                                                </div>
                                                @Html.Hidden("CodigoPrestador_" + i, item.Prestador.CodigoPrestador)
                                                @Html.Hidden("Rede_" + i, item.Prestador.CodigoRede)
                                                @Html.Hidden("NomePrestador_" + i, item.Prestador.DescricaoPrestador)
                                                @Html.Hidden("Registro_" + i, item.Prestador.DescricaoRegistro)
                                                @Html.Hidden("Endereco_" + i, string.Format("{0} {1}, {2}", item.Prestador.TipoLogradouro, item.Prestador.EnderecoRua, item.Prestador.EnderecoNumero))
                                                @Html.Hidden("Complemento_" + i, item.Prestador.EnderecoComplemento)
                                                @Html.Hidden("Bairro_" + i, item.Prestador.EnderecoBairro)
                                                @Html.Hidden("Cidade_" + i, item.Prestador.EnderecoCidade.Trim())
                                                @Html.Hidden("Cep_" + i, item.Prestador.CodigoCep)
                                                @Html.Hidden("SrEndereco_" + i, item.Prestador.SrEndereco)
                                                @Html.Hidden("Estado_" + i, item.Prestador.CodigoEstado)
                                                @Html.Hidden("DescricaoObservacao_" + i, item.Prestador.DescricaoObservacao)
                                                @Html.Hidden("DataDescredenciamento_" + i, item.Prestador.DataDescredenciamento)
                                                @Html.Hidden("NrAvaliacao_" + i, item.Prestador.NrAvaliacao)
                                                @Html.Hidden("Telefone_" + i, item.Prestador.TelefoneFormatado)
                                                @Html.Hidden("ScoreTotal_" + i, item.Prestador.ScoreTotal)
                                                @Html.Hidden("Latitude_" + i, item.Prestador.GmLatitude)
                                                @Html.Hidden("Longitude_" + i, item.Prestador.GmLongitude)
                                            </td>
                                        </tr>
                                        i++;
                                    }
                                </tbody>
                            </table>
                            <div class="row no-print" style="margin-left:30px">
                                @Html.PagedListPager(Model, page => Url.Action("PaginarPrestadoresProximidade", "Localizacao", new { page }))
                            </div>
                        }
                        else
                        {
                            <div class="col-lg-12">
                                @if (ViewBag.Erro != null)
                                {
                                    <span>@ViewBag.Erro</span>
                                }
                                else
                                {
                                    <span>A busca não gerou resultados!</span>
                                }
                            </div>
                        }

                    </div>
                </div>
            </div>
            <div class="col-xs-2 no-print">
                <div class="espaco-banner-img"
                     style="background-image: url(@Url.Content("~/Content/img/busca/medico-1.jpg"))">
                </div>
                <div class="espaco-banner-img"
                     style="background-image: url(@Url.Content("~/Content/img/busca/medico-2.jpg"))">
                </div>
                <div class="espaco-banner-img"
                     style="background-image: url(@Url.Content("~/Content/img/busca/medico-3.jpg"))">
                </div>
            </div>
        </div>
    </div>

</div>