MSW.Web/MSW.Web/Controllers/BuscaPrestadoresController.cs
using System;
using System.Linq;
using MSW.Web.Models;
using System.Web.Mvc;
using MSW.Web.Helpers;
using MSW.Web.Models.Request;
using MSW.Web.Models.Response;
using MSW.Web.Helpers.Extensions;
using Newtonsoft.Json;
using PagedList;
using System.Collections.Generic;
using System.Configuration;

namespace MSW.Web.Controllers
{
    public class BuscaPrestadoresController : PaginacaoController
    {
        private readonly OmintHttpRequest request = new OmintHttpRequest();

        public ActionResult Index()
        {
            string vinculo = Request.QueryString["Vinculo"] ?? Contexto.DadosUsuario?.Vinculo;
            ResultadoBuscaResponse buscaModel = new ResultadoBuscaResponse();

            if (!string.IsNullOrEmpty(vinculo) && Contexto.DadosUsuario == null)
            {
                ResultadoRequest response = request.Get("/RedeCredenciada/ObterDadosUsuario", new { vinculo = vinculo });

                if (response.Erro != null)
                {
                    ViewBag.Erro = response.Erro.Mensagem;
                    return View(buscaModel);
                }

                TituloResponse result = response.ObterResultado<TituloResponse>();

                Contexto.DadosUsuario = new DadosUsuario
                {
                    Vinculo = vinculo,
                    Enderecos = result.Data.Titulo.Enderecos,
                    DadosRede = result.Data.DadosRede
                };
            }

            buscaModel.Vinculo = vinculo;

            return View("ObterFormularioBusca", buscaModel);
        }

        [HttpPost]
        public ActionResult ObterFormularioBusca(FormularioBuscaRequest request)
        {
            ResultadoBuscaResponse response = new ResultadoBuscaResponse
            {
                CodigoRede = request.CodigoRede,
                DescricaoRede = request.Descricao,
                Plano = request.Plano
            };

            return PartialView("~/Views/Shared/_FormularioBuscaNome.cshtml", response);
        }

        [HttpPost]
        public ActionResult ResultadoBusca(BuscaNomeRequest request)
        {
            request.Vinculo = string.IsNullOrEmpty(request.Vinculo) ? Contexto.DadosUsuario?.Vinculo : request.Vinculo; 

            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterPorNome", request);
            ResultadoBuscaResponse redePrestadorResponse = new ResultadoBuscaResponse();

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;
                return View("~/Views/Resultados/ResultadoBusca.cshtml", redePrestadorResponse);
            }

            redePrestadorResponse = response.ObterResultado<ResultadoBuscaResponse>();
            List<Prestador> prestadores = redePrestadorResponse?.Data.OrderByDescending(x => x.ScoreTotal).ToList();

            if (prestadores != null)
            {
                string codigoRede = Contexto.ObterDados<string>(Consts.CODIGO_REDE);

                if (!string.IsNullOrEmpty(request.CodigoRede))
                {
                    if (request.CodigoRede != codigoRede)
                        Contexto.AdicionarDados(Consts.CODIGO_REDE, request.CodigoRede);
                }

                Contexto.AdicionarDados(Consts.RESULTADO_PESQUISA_SEM_FILTRO, prestadores);
                Contexto.AdicionarDados(Consts.LISTA_DADOS_PRESTADORES, prestadores);
                Contexto.AdicionarDados(Consts.TIPO_FILTRO_BUSCA, ContextoBuscaFiltro.BuscaPrestadores.ToString());
            }

            redePrestadorResponse.Nome = request.Nome;
            redePrestadorResponse.QuantidadeLocalizados = redePrestadorResponse.Data.Count;

            redePrestadorResponse.DefaultLat = redePrestadorResponse.Data?.Where(x => !string.IsNullOrEmpty(x.GmLatitude))?.FirstOrDefault()?.GmLatitude ?? Consts.LATITUDE_PADRAO_BRASIL;
            redePrestadorResponse.DefaultLng = redePrestadorResponse.Data?.Where(x => !string.IsNullOrEmpty(x.GmLongitude))?.FirstOrDefault()?.GmLongitude ?? Consts.LONGITUDE_PADRAO_BRASIL;
            redePrestadorResponse.MarcadoresGoogleMapsPosition = JsonConvert.SerializeObject(redePrestadorResponse.Data
                                                                                                                  ?.GroupBy(x => 
                                                                                                                  new
                                                                                                                  {
                                                                                                                     x.GmLatitude,
                                                                                                                     x.GmLongitude,
                                                                                                                     x.DescricaoPrestador
                                                                                                                  })
                                                                                                                  ?.Where(w => !string.IsNullOrEmpty(w.Key.GmLatitude) && !string.IsNullOrEmpty(w.Key.GmLongitude))
                                                                                                                  ?.Select(x => new { nome = x.Key.DescricaoPrestador, lat = x.Key.GmLatitude, lng = x.Key.GmLongitude }));
            ViewBag.PagedList = prestadores.ToPagedList(Consts.DEFAULT_PAGE_INIT, Consts.DEFAULT_PAGE_SIZE);
            return View("~/Views/Resultados/ResultadoBusca.cshtml", redePrestadorResponse);
        }

        [HttpPost]
        public ActionResult ResultadoBuscaAvancada(BuscaEspecialidadeRequest request)
        {
            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterPorEspecialidade", request);

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;
                return PartialView("~/Views/Resultados/_ResultadoBuscaAvancada.cshtml", new RedeEspecialidadeResponse());
            }

            RedeEspecialidadeResponse resultadoOperacao = response.ObterResultado<RedeEspecialidadeResponse>();
            return PartialView("~/Views/Resultados/_ResultadoBuscaAvancada.cshtml", resultadoOperacao);
        }

        [HttpPost]
        public ActionResult Detalhes(BuscaDetalhadaRequest request)
        {
            object reqParams = new
            {
                Rede = request.Rede,
                CodigoPrestador = request.CodigoPrestador,
                SrEndereco = request.SrEndereco,
                Inativos = request.Inativos
            };

            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterDetalhamento", reqParams);

            if (response.Erro != null)
            {
                ViewBag.Erro = response.Erro.Mensagem;
                return PartialView("~/Views/Resultados/_DetalhesBusca.cshtml", new DetalhamentoResponse());
            }

            DetalhamentoResponse resultadoOperacao = response.ObterResultado<DetalhamentoResponse>();

            ContextoBuscaFiltro contextoBusca;
            Enum.TryParse(Contexto.ObterDados<string>(Consts.TIPO_FILTRO_BUSCA), out contextoBusca);

            List<Prestador> prestadores = contextoBusca == ContextoBuscaFiltro.BuscaPrestadores ?
            Contexto.ObterDados<List<Prestador>>(Consts.LISTA_DADOS_PRESTADORES) :
            Contexto.ObterDados<List<DadosLocalizacao>>(Consts.LISTA_DADOS_PRESTADORES_PROXIMIDADE)?.Select(s => s.Prestador).ToList();

            resultadoOperacao.Data.Especialidades = prestadores.Where(p => p.CodigoPrestador == request.CodigoPrestador).FirstOrDefault()?.Especialidades ?? new List<string>();
            resultadoOperacao.Data.Telefones = prestadores.Where(p => p.CodigoPrestador == request.CodigoPrestador).FirstOrDefault()?.Telefones ?? new List<string>();

            RedeCredenciadaVinculo redeCredenciadaVinculo = Contexto.DadosUsuario?.DadosRede.RedeCredenciadaVinculo.FirstOrDefault(x => x.CodigoRede.Equals(request.Rede, StringComparison.OrdinalIgnoreCase));

            resultadoOperacao.NomePrestador = request.NomePrestador;
            resultadoOperacao.Rede = redeCredenciadaVinculo?.Descricao?? request.Rede;
            resultadoOperacao.Registro = request.Registro;
            resultadoOperacao.Bairro = request.Bairro;
            resultadoOperacao.CEP = request.CEP.FormatCep();
            resultadoOperacao.Cidade = $"{request.Cidade}/{request.Estado}";
            resultadoOperacao.Complemento = request.Complemento;
            resultadoOperacao.Endereco = request.Endereco;
            resultadoOperacao.DescricaoObservacao = request.DescricaoObservacao;
            resultadoOperacao.DataDescredenciamento = request.DataDescredenciamento;
            resultadoOperacao.CodigoPrestador = request.CodigoPrestador;
            resultadoOperacao.CodigoRede = request.Rede;
            resultadoOperacao.NrAvaliacao = request.NrAvaliacao;
            resultadoOperacao.Telefone = request.Telefone;
            resultadoOperacao.ScoreTotal = request.ScoreTotal;
            resultadoOperacao.Latitude = request.Latitude;
            resultadoOperacao.Longitude = request.Longitude;

            return PartialView("~/Views/Resultados/_DetalhesBusca.cshtml", resultadoOperacao);
        }

        [HttpPost]
        public ActionResult PlanosAtendidos(BuscaPlanosAtendidosRequest request)
        {
            object reqParams = new
            {
                Rede = request.Rede ?? Contexto.ObterDados<string>(Consts.CODIGO_REDE),
                CodigoPrestador = request.CodigoPrestador
            };

            ResultadoRequest response = this.request.Get("/RedeCredenciada/ObterPlanosAtendidos", reqParams);
            PlanosAtendidosResponse resultadoOperacao = new PlanosAtendidosResponse();

MSW.Web/MSW.Web/Views/BuscaPrestadores/BuscaAvancada.cshtml
@model BuscaEspecialidadeRequest

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-6">
        <span class="titulo-busca-rede">BUSCA DE REDE CREDENCIADA AVANÇADA</span>
    </div>
    <div class="col-lg-6" style="margin-top: 8px;">
        <span><a href="@Url.Action("BuscaEspecialidadeNome", "BuscaPrestadores", new { tipoAtendimento = "mediclin" })">Busca por especialidade</a></span>
    </div>
 
    <div class="col-xs-12" style="margin-top:50px;">
        <div class="col-xs-4 box-busca-avancada">
            <div class="texto-busca-avancada">
                <a href="@Url.Action("BuscaEspecialidade", "BuscaPrestadores", new { tipoAtendimento = "mediclin" })">
                    <span>Medicos e Clinicas</span>
                </a>
            </div>
        </div>
        <div class="col-xs-4 box-busca-avancada box-busca-avancada-espaco">
            <div class="texto-busca-avancada">
                <a href="@Url.Action("BuscaEspecialidade", "BuscaPrestadores", new { tipoAtendimento = "laborato" })">
                    <span>Centro de diagnosticos</span>
                </a>
            </div>
        </div>
        <div class="col-xs-4 box-busca-avancada box-busca-avancada-espaco">
            <div class="texto-busca-avancada">
                <a href="@Url.Action("BuscaEspecialidade", "BuscaPrestadores", new { tipoAtendimento = "hospital" })">
                    <span>Hospitais e maternidades</span>
                </a>
            </div>
        </div>
    </div>
    <div class="col-xs-12" style="margin-top:25px;">
        <div class="col-xs-4 box-busca-avancada">
            <div class="texto-busca-avancada">
                <a href="@Url.Action("BuscaEspecialidade", "BuscaPrestadores", new { tipoAtendimento = "prontsoc" })">
                    <span>Pronto atendimento</span>
                </a>
            </div>
        </div>
        <div class="col-xs-4 box-busca-avancada box-busca-avancada-espaco">
            <div class="texto-busca-avancada texto-busca-avancada-hospmat">
                <a href="@Url.Action("BuscaEspecialidade", "BuscaPrestadores", new { tipoAtendimento="pshospital" })">
                    <span>Hospitais e Pronto atendimento</span>
                </a>
            </div>
        </div>
        <div class="col-xs-4 box-busca-avancada box-busca-avancada-espaco">
            <div class="texto-busca-avancada texto-busca-avancada-odonto">
                <a href="@Url.Action("BuscaEspecialidade", "BuscaPrestadores", new { tipoAtendimento = "dentclin" })">
                    <span>Odontologia</span>
                </a>
            </div>
        </div>
    </div>   
</div>

<div class="row page_busca_legenda_qualificacoes" style="margin-left: -15px;">
    <div class="instrucoes_normativas_dides">
        <h4>Qualificações</h4>
        <hr>
        <p>Instrução Normativa 52/DIDES de 21/03/2013 </p>
    </div>
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_aona.jpg"></div>
                    Padrão nacional de qualidade
                </td>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_dicq.jpg"></div>
                    <span style="color: #000000;">Padrão nacional de qualidade</span>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_acba.jpg"></div>
                    Padrão internacional de qualidade
                </td>
                <td>
                    <div></div>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_palc.jpg"></div>
                    <span style="color: #000000;">Padrão nacional de qualidade</span>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_aqg.jpg"></div>
                    Padrão internacional de qualidade
                </td>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_r.jpg"></div>
                    Profissional com residência
                </td>
            </tr>
            <tr>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_n.jpg"></div>
                    Comunicação de eventos adversos
                </td>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_p.jpg"></div>
                    Profissional com especialização
                </td>
            </tr>
            <tr>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_q.jpg"></div>
                    Qualidade monitorada
                </td>
                <td>
                    <div class="col-xs-2"><img alt="" src="~/Content/img/busca/busca_e.jpg"></div>
                    Título de Especialista
                </td>
            </tr>
        </tbody>
    </table>
</div>

MSW.Web/MSW.Web/Views/BuscaPrestadores/BuscaEspecialidade.cshtml
@model BuscaEspecialidadeRequest

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="titulo-busca-avancada-omint">Encontre um Credenciado OMINT</h4>
    </div>
</div>
<div class="row row-space">
    <div class="col-lg-4">
        <span><a href="@Url.Action("BuscaAvancada", "BuscaPrestadores")">Voltar</a></span>
    </div>
</div>
<div class="row row-space">
    @Html.HiddenFor(x => x.Inativos)
    @Html.HiddenFor(x => x.Vinculo)
    @Html.HiddenFor(x => x.Rede)
    @Html.HiddenFor(x => x.TipoAtendimento)
</div>

<div class="row row-space-table" id="result">
    <div class="col-lg-6">
        <div class="result-omint-container" id="result">
            @Html.Partial("~/Views/Resultados/_ResultadoBuscaAvancada.cshtml", ViewData["resultadoOperacao"])
        </div>
    </div>
</div>

@section scripts {
    <script src="~/Content/js/busca.rede-credenciada.js"></script>
    <script>
        $(document).on('ready', function () {

            var buscaEspecialidade = new buscaRedeCredenciada.BuscaEspecialidade({
                urlBuscaLocalizacao: '@Url.Action("BuscaLocalizacao", "Localizacao")?',
                urlBuscaAvancada: '@Url.Action("ResultadoBuscaAvancada", "BuscaPrestadores")',
                divContainer: '#result'
            });

            $(document).on('click', '#btnBuscar', buscarPrestadores);
            $(document).on('click', '#btnBuscarEspecialidade', buscarPrestadoresEspecialidade);
            $(document).on('click', '[id^="especialidade_"]', manipularClickEspecialidade);

            function buscarPrestadores() {
                var nomeEspecialidade = $('#nome').val();

                if (nomeEspecialidade.length < 3 || nomeEspecialidade.trim().length < 3) {
                    alert('O campo de busca precisa ter pelo menos 3 caracteres!');
                    return;
                }

                $('#nome').val('');

                var data = {
                    inativos: $("#Inativos").val(),
                    vinculo: $("#Vinculo").val(),
                    rede: $('#Rede').val(),
                    tipoAtendimento: $('#TipoAtendimento').val(),
                    nomeEspecialidade: nomeEspecialidade
                };

                buscaEspecialidade.buscarPrestadores(data);
            }

            function buscarPrestadoresEspecialidade() {
                var data = {
                    inativos: $("#Inativos").val(),
                    nomeEspecialidade: $("#nome").val(),
                    vinculo: $("#Vinculo").val(),
                    rede: $('#Rede').val(),
                    tipoAtendimento: $('#TipoAtendimento').val()
                };

                buscaEspecialidade.buscarPrestadoresEspecialidade(data);
            }

            function manipularClickEspecialidade(e) {
                var data = {
                    tipoAtendimento: $('#TipoAtendimento').val(),
                    rede: $('#Rede').val()
                };

                buscaEspecialidade.onClickEspecialidade(e, data);
            }
        });

    </script>
}

MSW.Web/MSW.Web/Views/BuscaPrestadores/BuscaEspecialidadeNome.cshtml
@model BuscaEspecialidadeRequest

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <h4 class="titulo-busca-avancada-omint">Encontre um Credenciado OMINT</h4>
    </div>
</div>
<div class="row row-space">
    <div class="col-xs-4">
        <span><a href="@Url.Action("BuscaAvancada", "BuscaPrestadores")">Voltar</a></span>
    </div>

</div>
<div class="row row-space">
   <div class="col-xs-3">
       @Html.TextBoxFor(x => x.NomeEspecialidade, new { @placeholder="nome da especialidade",  @id="nome",  @style= "width:100%; border: 1px solid #A19062; height: 23px;" })
   </div>
    <div class="col-xs-3">
        <button type="button" id="btnBuscar" class="btn-omintexpress">Ok</button>
    </div>

    @Html.HiddenFor(x => x.Inativos)
    @Html.HiddenFor(x => x.Vinculo)
    @Html.HiddenFor(x => x.Rede)
    @Html.HiddenFor(x => x.TipoAtendimento)
</div>

<div class="row row-space-table" id="result">
    <div class="col-xs-6">
        <div class="result-omint-container" id="result">
        </div>
    </div>
</div>

@section scripts {
    <script src="~/Content/js/busca.rede-credenciada.js"></script>
    <script>
        $(document).on('ready', function () {

            var buscaEspecialidade = new buscaRedeCredenciada.BuscaEspecialidade({
                urlBuscaLocalizacao: '@Url.Action("BuscaLocalizacao", "Localizacao")?',
                urlBuscaAvancada: '@Url.Action("ResultadoBuscaAvancada", "BuscaPrestadores")',
                divContainer: '#result'
            });

            $(document).on('click', '#btnBuscar', buscarPrestadores);
            $(document).on('click', '#btnBuscarEspecialidade', buscarPrestadoresEspecialidade);
            $(document).on('click', '[id^="especialidade_"]', manipularClickEspecialidade);

            function buscarPrestadores() {
                var nomeEspecialidade = $('#nome').val();

                if (nomeEspecialidade.length < 3 || nomeEspecialidade.trim().length < 3) {
                    alert('O campo de busca precisa ter pelo menos 3 caracteres!');
                    return;
                }

                $('#nome').val('');

                var data = {
                    inativos: $("#Inativos").val(),
                    vinculo: $("#Vinculo").val(),
                    rede: $('#Rede').val(),
                    tipoAtendimento: $('#TipoAtendimento').val(),
                    nomeEspecialidade: nomeEspecialidade
                };


                buscaEspecialidade.buscarPrestadores(data);
            }

            function buscarPrestadoresEspecialidade() {
                var data = {
                    inativos: $("#Inativos").val(),
                    nomeEspecialidade: $("#nome").val(),
                    vinculo: $("#Vinculo").val(),
                    rede: $('#Rede').val(),
                    tipoAtendimento: $('#TipoAtendimento').val()
                };

                buscaEspecialidade.buscarPrestadoresEspecialidade(data);
            }

            function manipularClickEspecialidade(e) {
                var data = {
                    tipoAtendimento: $('#TipoAtendimento').val(),
                    rede: $('#Rede').val()
                };

                buscaEspecialidade.onClickEspecialidade(e, data);
            }
        });

    </script>
}

MSW.Web/MSW.Web/Views/BuscaPrestadores/ObterFormularioBusca.cshtml
@model ResultadoBuscaResponse
@{
    ViewBag.Title = "ObterFormularioBusca";
}

@using (Html.BeginForm("ResultadoBusca", "BuscaPrestadores", FormMethod.Post, new { @id = "formBusca" }))
{
    @Html.Partial("~/Views/Shared/_FormularioBuscaNome.cshtml", Model);
}

@section scripts
{
    <script>
        $('#formBusca').on('submit', function (e) {
            var nome = $('#Nome').val();

            if (nome.length < 3 || nome.trim().length < 3) {
                alert('O campo de busca precisa ter pelo menos 3 caracteres!');
                return false;
            }

            window.parent.postMessage("esconder-header", "*");
        });
    </script>
}